swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "TWSE"
host: "127.0.0.1:5000"
basePath: "/v1"
schemes:
- "https"
- "http"
paths:
  /stock/{code}:
    get:
      summary: "依照證券代號搜尋最近n天的資料"
      produces:
        - "application/json"
      parameters:
        - name: "code"
          in: "path"
          description: "證券代號"
          required: true
          type: "integer"
          format: "int"
        - name: "count"
          in: "query"
          description: "n天"
          type: "integer"
          format: "int"
      responses:
        "200":
          description: "successful"
          schema:
            $ref: "#/definitions/Stock"
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
        - api_key: []
  /ranking/{date}:
    get:
      summary: "指定特定日期顯示當天本益比前n名"
      produces:
        - "application/json"
      parameters:
        - name: "date"
          in: "path"
          description: "指定特定日期"
          required: true
          type: "string"
        - name: "count"
          in: "query"
          description: "前n名"
          type: "integer"
          format: "int"
      responses:
        "200":
          description: "successful"
          schema:
            $ref: "#/definitions/Ranking"
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
        - api_key: []
  /dividend/{code}:
    get:
      summary: "指定日期範圍、證券代號顯示這段時間內殖利率為嚴格遞增的最長天數並顯示開始、結束日期"
      produces:
        - "application/json"
      parameters:
        - name: "code"
          in: "path"
          description: "證券代號"
          required: true
          type: "integer"
          format: "int"
        - name: "being"
          in: "query"
          description: "開始日期"
          type: "string"
          format: "yyyyMMdd"
        - name: "end"
          in: "query"
          description: "結束日期"
          type: "string"
          format: "yyyyMMdd"
      responses:
        "200":
          description: "successful"
          schema:
            $ref: "#/definitions/Dividend"
        "400":
          description: ""
        "404":
          description: ""
        "500":
          description: ""
      security:
        - api_key: []
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "X-API-Key"
    in: "header"
definitions:
  Stock:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "證券代號"
        format: "int"
      date:
        type: "string"
        description: "日期"
      name:
        type: "string"
        description: "證券名稱"
      pe:
        type: "number"
        description: "本益比"
        format: "float"
      pb:
        type: "number"
        description: "股價淨值比"
        format: "float"
      yield:
        type: "number"
        description: "殖利率(%)"
        format: "float"
      year:
        type: "string"
        description: "股利年度"
      fiscal:
        type: "string"
        description: "財報年/季"
  Ranking:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "證券代號"
        format: "int"
      date:
        type: "string"
        description: "日期"
      name:
        type: "string"
        description: "證券名稱"
      pe:
        type: "number"
        description: "本益比"
        format: "float"
  Dividend:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "證券代號"
        format: "int"
      days:
        type: "integer"
        description: "最長天數"
      begin:
        type: "string"
        description: "開始日期"
      end:
        type: "string"
        description: "結束日期"
        format: "float"